version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    command: sleep infinity
    volumes:
      - ..:/cypher-dto:cached
    environment:
      PROJECT_ROOT: /cypher-dto
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      TZ: ${TZ}
      NEO4J_TEST_URI: "bolt://db:7687"
      NEO4J_TEST_USER: "neo4j"
      NEO4J_TEST_PASS: "developer"

  db:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db_data:/data
      - db_logs:/logs
    environment:
      NEO4J_AUTH: neo4j/developer

volumes:
  db_data:
  db_logs:
